
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The system is: Windows - 10.0.22000 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      MSBuild version 17.7.2+d6990bcfa for .NET Framework
      Build started 27 Sep 2023 11:21:45.
      
      Project "C:\\Users\\elo48\\OneDrive\\Documents\\C and C++ Programs\\ricky-ultimate\\cpp-simple-mensuration-calculator\\CMakeFiles\\3.27.6\\CompilerIdC\\CompilerIdC.vcxproj" on node 1 (default targets).
      PrepareForBuild:
        Creating directory "Debug\\".
        Creating directory "Debug\\CompilerIdC.tlog\\".
      InitializeBuildStatus:
        Creating "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
        Touching "Debug\\CompilerIdC.tlog\\unsuccessfulbuild".
      ClCompile:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> C:\\Users\\elo48\\OneDrive\\Documents\\C and C++ Programs\\ricky-ultimate\\cpp-simple-mensuration-calculator\\CMakeFiles\\3.27.6\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.37.32822\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Deleting file "Debug\\CompilerIdC.tlog\\unsuccessfulbuild".
        Touching "Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate".
      Done Building Project "C:\\Users\\elo48\\OneDrive\\Documents\\C and C++ Programs\\ricky-ultimate\\cpp-simple-mensuration-calculator\\CMakeFiles\\3.27.6\\CompilerIdC\\CompilerIdC.vcxproj" (default targets).
      
      Build succeeded.
          0 Warning(s)
          0 Error(s)
      
      Time Elapsed 00:00:07.37
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        C:/Users/elo48/OneDrive/Documents/C and C++ Programs/ricky-ultimate/cpp-simple-mensuration-calculator/CMakeFiles/3.27.6/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      MSBuild version 17.7.2+d6990bcfa for .NET Framework
      Build started 27 Sep 2023 11:21:54.
      
      Project "C:\\Users\\elo48\\OneDrive\\Documents\\C and C++ Programs\\ricky-ultimate\\cpp-simple-mensuration-calculator\\CMakeFiles\\3.27.6\\CompilerIdCXX\\CompilerIdCXX.vcxproj" on node 1 (default targets).
      PrepareForBuild:
        Creating directory "Debug\\".
        Creating directory "Debug\\CompilerIdCXX.tlog\\".
      InitializeBuildStatus:
        Creating "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
        Touching "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild".
      ClCompile:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> C:\\Users\\elo48\\OneDrive\\Documents\\C and C++ Programs\\ricky-ultimate\\cpp-simple-mensuration-calculator\\CMakeFiles\\3.27.6\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.37.32822\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Deleting file "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild".
        Touching "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate".
      Done Building Project "C:\\Users\\elo48\\OneDrive\\Documents\\C and C++ Programs\\ricky-ultimate\\cpp-simple-mensuration-calculator\\CMakeFiles\\3.27.6\\CompilerIdCXX\\CompilerIdCXX.vcxproj" (default targets).
      
      Build succeeded.
          0 Warning(s)
          0 Error(s)
      
      Time Elapsed 00:00:05.22
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        C:/Users/elo48/OneDrive/Documents/C and C++ Programs/ricky-ultimate/cpp-simple-mensuration-calculator/CMakeFiles/3.27.6/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/elo48/OneDrive/Documents/C and C++ Programs/ricky-ultimate/cpp-simple-mensuration-calculator/CMakeFiles/CMakeScratch/TryCompile-ggbegu"
      binary: "C:/Users/elo48/OneDrive/Documents/C and C++ Programs/ricky-ultimate/cpp-simple-mensuration-calculator/CMakeFiles/CMakeScratch/TryCompile-ggbegu"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS /W3"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/elo48/OneDrive/Documents/C and C++ Programs/ricky-ultimate/cpp-simple-mensuration-calculator/CMakeFiles/CMakeScratch/TryCompile-ggbegu'
        
        Run Build Command(s): "C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_e4c71.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        MSBuild version 17.7.2+d6990bcfa for .NET Framework
        Build started 27 Sep 2023 11:22:03.
        
        Project "C:\\Users\\elo48\\OneDrive\\Documents\\C and C++ Programs\\ricky-ultimate\\cpp-simple-mensuration-calculator\\CMakeFiles\\CMakeScratch\\TryCompile-ggbegu\\cmTC_e4c71.vcxproj" on node 1 (default targets).
        PrepareForBuild:
          Creating directory "cmTC_e4c71.dir\\Debug\\".
          Creating directory "C:\\Users\\elo48\\OneDrive\\Documents\\C and C++ Programs\\ricky-ultimate\\cpp-simple-mensuration-calculator\\CMakeFiles\\CMakeScratch\\TryCompile-ggbegu\\Debug\\".
          Creating directory "cmTC_e4c71.dir\\Debug\\cmTC_e4c71.tlog\\".
        InitializeBuildStatus:
          Creating "cmTC_e4c71.dir\\Debug\\cmTC_e4c71.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
          Touching "cmTC_e4c71.dir\\Debug\\cmTC_e4c71.tlog\\unsuccessfulbuild".
        ClCompile:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_e4c71.dir\\Debug\\\\" /Fd"cmTC_e4c71.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.27\\Modules\\CMakeCCompilerABI.c"
          Microsoft (R) C/C++ Optimizing Compiler Version 19.37.32824 for x64
          CMakeCCompilerABI.c
          Copyright (C) Microsoft Corporation.  All rights reserved.
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_e4c71.dir\\Debug\\\\" /Fd"cmTC_e4c71.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.27\\Modules\\CMakeCCompilerABI.c"
        Link:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\elo48\\OneDrive\\Documents\\C and C++ Programs\\ricky-ultimate\\cpp-simple-mensuration-calculator\\CMakeFiles\\CMakeScratch\\TryCompile-ggbegu\\Debug\\cmTC_e4c71.exe" /INCREMENTAL /ILK:"cmTC_e4c71.dir\\Debug\\cmTC_e4c71.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/elo48/OneDrive/Documents/C and C++ Programs/ricky-ultimate/cpp-simple-mensuration-calculator/CMakeFiles/CMakeScratch/TryCompile-ggbegu/Debug/cmTC_e4c71.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/elo48/OneDrive/Documents/C and C++ Programs/ricky-ultimate/cpp-simple-mensuration-calculator/CMakeFiles/CMakeScratch/TryCompile-ggbegu/Debug/cmTC_e4c71.lib" /MACHINE:X64  /machine:x64 cmTC_e4c71.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_e4c71.vcxproj -> C:\\Users\\elo48\\OneDrive\\Documents\\C and C++ Programs\\ricky-ultimate\\cpp-simple-mensuration-calculator\\CMakeFiles\\CMakeScratch\\TryCompile-ggbegu\\Debug\\cmTC_e4c71.exe
        FinalizeBuildStatus:
          Deleting file "cmTC_e4c71.dir\\Debug\\cmTC_e4c71.tlog\\unsuccessfulbuild".
          Touching "cmTC_e4c71.dir\\Debug\\cmTC_e4c71.tlog\\cmTC_e4c71.lastbuildstate".
        Done Building Project "C:\\Users\\elo48\\OneDrive\\Documents\\C and C++ Programs\\ricky-ultimate\\cpp-simple-mensuration-calculator\\CMakeFiles\\CMakeScratch\\TryCompile-ggbegu\\cmTC_e4c71.vcxproj" (default targets).
        
        Build succeeded.
            0 Warning(s)
            0 Error(s)
        
        Time Elapsed 00:00:09.57
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/Users/elo48/OneDrive/Documents/C and C++ Programs/ricky-ultimate/cpp-simple-mensuration-calculator/CMakeFiles/CMakeScratch/TryCompile-cq0ef5"
      binary: "C:/Users/elo48/OneDrive/Documents/C and C++ Programs/ricky-ultimate/cpp-simple-mensuration-calculator/CMakeFiles/CMakeScratch/TryCompile-cq0ef5"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/elo48/OneDrive/Documents/C and C++ Programs/ricky-ultimate/cpp-simple-mensuration-calculator/CMakeFiles/CMakeScratch/TryCompile-cq0ef5'
        
        Run Build Command(s): "C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_fabc0.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        MSBuild version 17.7.2+d6990bcfa for .NET Framework
        Build started 27 Sep 2023 11:22:14.
        
        Project "C:\\Users\\elo48\\OneDrive\\Documents\\C and C++ Programs\\ricky-ultimate\\cpp-simple-mensuration-calculator\\CMakeFiles\\CMakeScratch\\TryCompile-cq0ef5\\cmTC_fabc0.vcxproj" on node 1 (default targets).
        PrepareForBuild:
          Creating directory "cmTC_fabc0.dir\\Debug\\".
          Creating directory "C:\\Users\\elo48\\OneDrive\\Documents\\C and C++ Programs\\ricky-ultimate\\cpp-simple-mensuration-calculator\\CMakeFiles\\CMakeScratch\\TryCompile-cq0ef5\\Debug\\".
          Creating directory "cmTC_fabc0.dir\\Debug\\cmTC_fabc0.tlog\\".
        InitializeBuildStatus:
          Creating "cmTC_fabc0.dir\\Debug\\cmTC_fabc0.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
          Touching "cmTC_fabc0.dir\\Debug\\cmTC_fabc0.tlog\\unsuccessfulbuild".
        ClCompile:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_fabc0.dir\\Debug\\\\" /Fd"cmTC_fabc0.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.27\\Modules\\CMakeCXXCompilerABI.cpp"
          Microsoft (R) C/C++ Optimizing Compiler Version 19.37.32824 for x64
          CMakeCXXCompilerABI.cpp
          Copyright (C) Microsoft Corporation.  All rights reserved.
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_fabc0.dir\\Debug\\\\" /Fd"cmTC_fabc0.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.27\\Modules\\CMakeCXXCompilerABI.cpp"
        Link:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\elo48\\OneDrive\\Documents\\C and C++ Programs\\ricky-ultimate\\cpp-simple-mensuration-calculator\\CMakeFiles\\CMakeScratch\\TryCompile-cq0ef5\\Debug\\cmTC_fabc0.exe" /INCREMENTAL /ILK:"cmTC_fabc0.dir\\Debug\\cmTC_fabc0.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/elo48/OneDrive/Documents/C and C++ Programs/ricky-ultimate/cpp-simple-mensuration-calculator/CMakeFiles/CMakeScratch/TryCompile-cq0ef5/Debug/cmTC_fabc0.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/elo48/OneDrive/Documents/C and C++ Programs/ricky-ultimate/cpp-simple-mensuration-calculator/CMakeFiles/CMakeScratch/TryCompile-cq0ef5/Debug/cmTC_fabc0.lib" /MACHINE:X64  /machine:x64 cmTC_fabc0.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_fabc0.vcxproj -> C:\\Users\\elo48\\OneDrive\\Documents\\C and C++ Programs\\ricky-ultimate\\cpp-simple-mensuration-calculator\\CMakeFiles\\CMakeScratch\\TryCompile-cq0ef5\\Debug\\cmTC_fabc0.exe
        FinalizeBuildStatus:
          Deleting file "cmTC_fabc0.dir\\Debug\\cmTC_fabc0.tlog\\unsuccessfulbuild".
          Touching "cmTC_fabc0.dir\\Debug\\cmTC_fabc0.tlog\\cmTC_fabc0.lastbuildstate".
        Done Building Project "C:\\Users\\elo48\\OneDrive\\Documents\\C and C++ Programs\\ricky-ultimate\\cpp-simple-mensuration-calculator\\CMakeFiles\\CMakeScratch\\TryCompile-cq0ef5\\cmTC_fabc0.vcxproj" (default targets).
        
        Build succeeded.
            0 Warning(s)
            0 Error(s)
        
        Time Elapsed 00:00:03.61
        
      exitCode: 0
...
